2016-11-07T20:46:52-0500 [-] Unable to write to plugin cache /Library/Python/2.7/site-packages/twisted/plugins/dropin.cache: error number 13
2016-11-07T20:46:52-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.3.0 (/usr/bin/python 2.7.10) starting up.
2016-11-07T20:46:52-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2016-11-07T20:46:52-0500 [-] Site starting on 10000
2016-11-07T20:46:52-0500 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x10ba77248>
2016-11-07T20:46:56-0500 [twisted.logger._global#warn] /Library/Python/2.7/site-packages/twisted/web/wsgi.py:128: exceptions.UnicodeWarning: write() argument should be str, not u'[2016-11-07 20:46:56,354] ERROR in app: Exception on /searchUser/Holden [GET]\nTraceback (most recent call last):\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 154, in searchUser\n    cursorclass=MySQLdb.cursors.DictCursor)        # name of the data base\n  File "/Library/Python/2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect\n    return Connection(*args, **kwargs)\n  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 193, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\nOperationalError: (1049, "Unknown database \'Liars\'")\n' (unicode)
2016-11-07T20:46:56-0500 [wsgi] [2016-11-07 20:46:56,354] ERROR in app: Exception on /searchUser/Holden [GET]
	Traceback (most recent call last):
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
	    response = self.full_dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
	    rv = self.handle_user_exception(e)
	  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
	    return original_handler(e)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
	    reraise(exc_type, exc_value, tb)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
	    rv = self.dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
	    return self.view_functions[rule.endpoint](**req.view_args)
	  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 154, in searchUser
	    cursorclass=MySQLdb.cursors.DictCursor)        # name of the data base
	  File "/Library/Python/2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
	    return Connection(*args, **kwargs)
	  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
	    super(Connection, self).__init__(*args, **kwargs2)
	OperationalError: (1049, "Unknown database 'Liars'")
	
2016-11-07T20:46:56-0500 [twisted.python.log#info] "127.0.0.1" - - [08/Nov/2016:01:46:55 +0000] "GET /searchUser/Holden HTTP/1.1" 500 291 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
2016-11-07T20:50:30-0500 [-] Received SIGTERM, shutting down.
2016-11-07T20:50:30-0500 [-] (TCP Port 10000 Closed)
2016-11-07T20:50:30-0500 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x10ba77248>
2016-11-07T20:50:30-0500 [-] Main loop terminated.
2016-11-07T20:50:30-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
2016-11-07T20:51:27-0500 [-] Unable to write to plugin cache /Library/Python/2.7/site-packages/twisted/plugins/dropin.cache: error number 13
2016-11-07T20:51:27-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.3.0 (/usr/bin/python 2.7.10) starting up.
2016-11-07T20:51:27-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2016-11-07T20:51:27-0500 [-] Site starting on 10000
2016-11-07T20:51:27-0500 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x10b9c7248>
2016-11-07T20:52:03-0500 [-] Received SIGTERM, shutting down.
2016-11-07T20:52:03-0500 [-] (TCP Port 10000 Closed)
2016-11-07T20:52:03-0500 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x10b9c7248>
2016-11-07T20:52:03-0500 [-] Main loop terminated.
2016-11-07T20:52:03-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
2016-11-07T20:52:05-0500 [-] Unable to write to plugin cache /Library/Python/2.7/site-packages/twisted/plugins/dropin.cache: error number 13
2016-11-07T20:52:05-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.3.0 (/usr/bin/python 2.7.10) starting up.
2016-11-07T20:52:05-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2016-11-07T20:52:05-0500 [-] Site starting on 10000
2016-11-07T20:52:05-0500 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x10e575e60>
2016-11-07T20:52:23-0500 [twisted.logger._global#warn] /Library/Python/2.7/site-packages/twisted/web/wsgi.py:128: exceptions.UnicodeWarning: write() argument should be str, not u'[2016-11-07 20:52:23,198] ERROR in app: Exception on /searchUser/Holden [GET]\nTraceback (most recent call last):\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 154, in searchUser\n    cursorclass=MySQLdb.cursors.DictCursor)        # name of the data base\n  File "/Library/Python/2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect\n    return Connection(*args, **kwargs)\n  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 193, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\nOperationalError: (1049, "Unknown database \'Liars\'")\n' (unicode)
2016-11-07T20:52:23-0500 [wsgi] [2016-11-07 20:52:23,198] ERROR in app: Exception on /searchUser/Holden [GET]
	Traceback (most recent call last):
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
	    response = self.full_dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
	    rv = self.handle_user_exception(e)
	  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
	    return original_handler(e)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
	    reraise(exc_type, exc_value, tb)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
	    rv = self.dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
	    return self.view_functions[rule.endpoint](**req.view_args)
	  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 154, in searchUser
	    cursorclass=MySQLdb.cursors.DictCursor)        # name of the data base
	  File "/Library/Python/2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
	    return Connection(*args, **kwargs)
	  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
	    super(Connection, self).__init__(*args, **kwargs2)
	OperationalError: (1049, "Unknown database 'Liars'")
	
2016-11-07T20:52:23-0500 [twisted.python.log#info] "127.0.0.1" - - [08/Nov/2016:01:52:22 +0000] "GET /searchUser/Holden HTTP/1.1" 500 291 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
2016-11-07T20:53:09-0500 [-] Received SIGTERM, shutting down.
2016-11-07T20:53:09-0500 [-] (TCP Port 10000 Closed)
2016-11-07T20:53:09-0500 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x10e575e60>
2016-11-07T20:53:09-0500 [-] Main loop terminated.
2016-11-07T20:53:09-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
2016-11-07T20:53:48-0500 [-] Unable to write to plugin cache /Library/Python/2.7/site-packages/twisted/plugins/dropin.cache: error number 13
2016-11-07T20:53:48-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.3.0 (/usr/bin/python 2.7.10) starting up.
2016-11-07T20:53:48-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2016-11-07T20:53:48-0500 [-] Site starting on 10000
2016-11-07T20:53:48-0500 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x1110bb248>
2016-11-07T20:53:52-0500 [twisted.logger._global#warn] /Library/Python/2.7/site-packages/twisted/web/wsgi.py:128: exceptions.UnicodeWarning: write() argument should be str, not u'[2016-11-07 20:53:52,701] ERROR in app: Exception on /searchUser/Holden [GET]\nTraceback (most recent call last):\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 154, in searchUser\n    cursorclass=MySQLdb.cursors.DictCursor)        # name of the data base\n  File "/Library/Python/2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect\n    return Connection(*args, **kwargs)\n  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 193, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\nOperationalError: (1049, "Unknown database \'Liars\'")\n' (unicode)
2016-11-07T20:53:52-0500 [wsgi] [2016-11-07 20:53:52,701] ERROR in app: Exception on /searchUser/Holden [GET]
	Traceback (most recent call last):
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
	    response = self.full_dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
	    rv = self.handle_user_exception(e)
	  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
	    return original_handler(e)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
	    reraise(exc_type, exc_value, tb)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
	    rv = self.dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
	    return self.view_functions[rule.endpoint](**req.view_args)
	  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 154, in searchUser
	    cursorclass=MySQLdb.cursors.DictCursor)        # name of the data base
	  File "/Library/Python/2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
	    return Connection(*args, **kwargs)
	  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
	    super(Connection, self).__init__(*args, **kwargs2)
	OperationalError: (1049, "Unknown database 'Liars'")
	
2016-11-07T20:53:52-0500 [twisted.python.log#info] "127.0.0.1" - - [08/Nov/2016:01:53:51 +0000] "GET /searchUser/Holden HTTP/1.1" 500 291 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
2016-11-07T20:55:46-0500 [-] Received SIGTERM, shutting down.
2016-11-07T20:55:46-0500 [-] (TCP Port 10000 Closed)
2016-11-07T20:55:46-0500 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x1110bb248>
2016-11-07T20:55:46-0500 [-] Main loop terminated.
2016-11-07T20:55:46-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
2016-11-07T20:55:47-0500 [-] Unable to write to plugin cache /Library/Python/2.7/site-packages/twisted/plugins/dropin.cache: error number 13
2016-11-07T20:55:47-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.3.0 (/usr/bin/python 2.7.10) starting up.
2016-11-07T20:55:47-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2016-11-07T20:55:47-0500 [-] Site starting on 10000
2016-11-07T20:55:47-0500 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x10198ce60>
2016-11-07T20:55:50-0500 [twisted.logger._global#warn] /Library/Python/2.7/site-packages/twisted/web/wsgi.py:128: exceptions.UnicodeWarning: write() argument should be str, not u'[2016-11-07 20:55:50,616] ERROR in app: Exception on /searchUser/Holden [GET]\nTraceback (most recent call last):\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 222, in searchUser\n    cur.execute("SELECT name, username, id, device_token, " + masterMatchString + " FROM Users HAVING " + additionString + " > 0.1 " + "ORDER BY " + additionString + " DESC")\n  File "/Library/Python/2.7/site-packages/MySQLdb/cursors.py", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (1191, "Can\'t find FULLTEXT index matching the column list")\n' (unicode)
2016-11-07T20:55:50-0500 [wsgi] [2016-11-07 20:55:50,616] ERROR in app: Exception on /searchUser/Holden [GET]
	Traceback (most recent call last):
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
	    response = self.full_dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
	    rv = self.handle_user_exception(e)
	  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
	    return original_handler(e)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
	    reraise(exc_type, exc_value, tb)
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
	    rv = self.dispatch_request()
	  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
	    return self.view_functions[rule.endpoint](**req.view_args)
	  File "/Users/wtobey/Desktop/LiarsBackend/LiarsREST.py", line 222, in searchUser
	    cur.execute("SELECT name, username, id, device_token, " + masterMatchString + " FROM Users HAVING " + additionString + " > 0.1 " + "ORDER BY " + additionString + " DESC")
	  File "/Library/Python/2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
	    self.errorhandler(self, exc, value)
	  File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	OperationalError: (1191, "Can't find FULLTEXT index matching the column list")
	
2016-11-07T20:55:50-0500 [twisted.python.log#info] "127.0.0.1" - - [08/Nov/2016:01:55:49 +0000] "GET /searchUser/Holden HTTP/1.1" 500 291 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
2016-11-07T20:57:05-0500 [-] Received SIGTERM, shutting down.
2016-11-07T20:57:05-0500 [-] (TCP Port 10000 Closed)
2016-11-07T20:57:05-0500 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x10198ce60>
2016-11-07T20:57:05-0500 [-] Main loop terminated.
2016-11-07T20:57:05-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
2016-11-07T20:57:06-0500 [-] Unable to write to plugin cache /Library/Python/2.7/site-packages/twisted/plugins/dropin.cache: error number 13
2016-11-07T20:57:06-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.3.0 (/usr/bin/python 2.7.10) starting up.
2016-11-07T20:57:06-0500 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2016-11-07T20:57:06-0500 [-] Site starting on 10000
2016-11-07T20:57:06-0500 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x1089e2e60>
2016-11-07T20:57:08-0500 [twisted.python.log#info] "127.0.0.1" - - [08/Nov/2016:01:57:08 +0000] "GET /searchUser/Holden HTTP/1.1" 0 382 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
2016-11-07T21:21:09-0500 [twisted.python.log#info] "127.0.0.1" - - [08/Nov/2016:02:21:09 +0000] "GET /searchUser/Harry HTTP/1.1" 0 347 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
